config/routes.rb
Rails.application.routes.draw do
  resources :bugcats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bugcat.rb
class Bugcat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bugcats_controller.rb
class BugcatsController < ApplicationController
  def index
    @bugcats = Bugcat
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bugcats_helper.rb
module BugcatsHelper
end

app/views/bugcats/index.html.erb
<h1>貓貓蟲們</h1>

<%= link_to "新貓貓蟲", new_bugcat_path %>

<table>
  <thead>
    <tr>
      <td>貓貓蟲姓名</td>
      <td>參加政黨</td>
      <td>政見發表</td>
      <td>得票數</td>
    </tr>
  </thead>
  <tbody>
    <% @bugcats.each do |bugcats| %>
    <tr>
      <td><%= bugcat.name %>(年齡：<%= bugcat.age %> 歲)</td>
      <td><%= bugcat.party %></td>
      <td><%= bugcat.politics %></td>
      <td><%= bugcat.votes %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bugcat</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>